[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = "f21da20092d77f52d7977bd5f0e6b071"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  # Force App Router
  NEXT_PRIVATE_PREBUNDLED_REACT = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect all requests to the App Router
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
  force = true