[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = "f21da20092d77f52d7977bd5f0e6b071"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# These redirects are handled by Next.js internally, so we don't need them
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200